### ISSUE TITLE
qq号被封了吗

### ISSUE THREAD

**Issue by FuGuangzhi1** [HyperLife1119/ngx-fluent-form#122]
佬qq号被封了吗，一天没水群
![EW174 6JIVN_EIWMHEW%EUB](https://github.com/HyperLife1119/ngx-fluent-form/assets/87634542/b225bdcd-e936-4190-969c-87a8e08145b5)

**Comment by HyperLife1119** [comment]
冻结7天

**Comment by fengluoX** [comment]
刺激
